/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_use_ndk_build_MainActivity */

#ifndef _Included_com_example_use_ndk_build_MainActivity
#define _Included_com_example_use_ndk_build_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_use_ndk_build_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_use_ndk_build_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_use_ndk_build_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_use_1ndk_1build_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_use_ndk_build_MainActivity
 * Method:    ConvertGraytoCanny
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_com_example_use_1ndk_1build_MainActivity_ConvertGraytoCanny
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_example_use_ndk_build_MainActivity
 * Method:    ConvertCannytoHoughp
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_com_example_use_1ndk_1build_MainActivity_ConvertCannytoHoughp
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
